package com.example.faculty.entity;
import jakarta.persistence.*;
import lombok.*;
import java.util.*;
@Entity
@Table(name="faculty")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Faculty {
    //Surrogate Primary key
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /* Unique employee ID assigned by the system.
    This is NOT auto-generated by JPA.
    Will be generated manually in the Service layer.
     */
    @Column(nullable=false,unique=true)
    private String employeeId;

    //Full name
    @Column(nullable=false)
    private String fullName;

    //Email
    @Column(nullable=false,unique = true)
    private String email;

    //Phone number
    @Column(nullable=false,unique = true)
    private String phoneNumber;

    //Path to the faculty photo
    private String photoPath;

    /*
     * Each faculty belongs to ONE department.
     * Many faculty -> One department.
     */
    @ManyToOne
    @JoinColumn(name="department_id",nullable=false)
    private Department department;

    /*
     * Many-to-Many relationship:
     * A faculty can teach MANY courses.
     * A course can be taught by MANY faculty.
     *
     * We use a join table "faculty_course" to store the relationship.
     */
    @ManyToMany
    @JoinTable(
            name="faculty_course",
            joinColumns=@JoinColumn(name="faculty_id"),
            inverseJoinColumns=@JoinColumn(name="course_id")
    )
    private List<Course> courses;
}
